// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvxEiqBL6VtEno6gaCczeOVXGsyV-lsS8',
    appId: '1:843970343429:web:39235bff7f1e7e7f3ba26c',
    messagingSenderId: '843970343429',
    projectId: 'project0-658f8',
    authDomain: 'project0-658f8.firebaseapp.com',
    storageBucket: 'project0-658f8.firebasestorage.app',
    measurementId: 'G-NGF0NVRVHH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzZUw7HALjxVjhYvVV40M-NeM7BavSyWQ',
    appId: '1:843970343429:android:f6cf458ffc64e1d33ba26c',
    messagingSenderId: '843970343429',
    projectId: 'project0-658f8',
    storageBucket: 'project0-658f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj1bgozQcriKPdh6EM-D2KPyqep2MOLJY',
    appId: '1:843970343429:ios:918b60b17696166d3ba26c',
    messagingSenderId: '843970343429',
    projectId: 'project0-658f8',
    storageBucket: 'project0-658f8.firebasestorage.app',
    iosBundleId: 'com.example.nikeshoes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj1bgozQcriKPdh6EM-D2KPyqep2MOLJY',
    appId: '1:843970343429:ios:918b60b17696166d3ba26c',
    messagingSenderId: '843970343429',
    projectId: 'project0-658f8',
    storageBucket: 'project0-658f8.firebasestorage.app',
    iosBundleId: 'com.example.nikeshoes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVuwQP1_d_Mk-_Oumv4YeENcWCZyNqWmo',
    appId: '1:843970343429:web:4422242a35df4e463ba26c',
    messagingSenderId: '843970343429',
    projectId: 'project0-658f8',
    authDomain: 'project0-658f8.firebaseapp.com',
    storageBucket: 'project0-658f8.firebasestorage.app',
    measurementId: 'G-FKW9QTJML6',
  );
}
